/*
 * This source file was generated by the Gradle 'init' task
 */
package com.collo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TwoSumTest {
    @Test void someLibraryMethodReturnsTrue() {
        TwoSum classUnderTest = new TwoSum();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
